kube-prometheus-stack:
  alertmanager:
    enabled: false

  grafana:
    enabled: false

  prometheus:
    enabled: true
    prometheusSpec:
      retention: 7d
      serviceMonitorSelectorNilUsesHelmValues: true
      podMonitorSelectorNilUsesHelmValues: true
      ruleSelectorNilUsesHelmValues: true
      enableRemoteWriteReceiver: true
      maximumStartupDurationSeconds: 300
      remoteWrite:
        - url: http://mimir-nginx.mimir.svc.cluster.local/api/v1/push
          headers:
            X-Scope-OrgID: prometheus
          queueConfig:
            maxSamplesPerSend: 1000
            maxShards: 200
            capacity: 2500

  kubeStateMetrics:
    enabled: true

prometheus-node-exporter:
  enabled: true
  tolerations:
    - operator: "Exists"
