external-dns:
  serviceAccount:
    create: true
    name: external-dns-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::880076045111:role/external-dns-sa-role
  domainFilters:
    - kimdongju.site 
  serviceMonitor:
    enabled: true