### Deployment
replicaCount: 2

image:
  repository: dongjukim123/soundory-fe
  pullPolicy: IfNotPresent
  tag: 7

container:
  port: 80  

terminationGracePeriodSeconds: 10

resources:
  limits:
    memory: 128Mi
    cpu: 200m
  requests:
    memory: 64Mi
    cpu: 50m

### toleration & affinity
nodeSelector: {}
tolerations:
  - key: "node"
    operator: "Equal"
    value: "service"
    effect: "NoSchedule"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role
              operator: In
              values:
                - service

podAnnotations: {}

### Health Check
probes:
  liveness:
    enabled: false
    path: /
  readiness:
    enabled: false
    path: /

### HPA
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
  targetMemoryUtilizationPercentage: 50

### Service
service:
  type: ClusterIP
  port: 80
  targetPort: 80
  
### Ingress
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: soundory-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/success-codes: '200,302'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:880076045111:certificate/b08ddabe-0314-42dc-bdbf-8701d3993c69
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    external-dns.alpha.kubernetes.io/hostname: kimdongju.site

  hosts:
    - host: kimdongju.site
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - kimdongju.site

### Misc
pvc:
  enabled: false

serviceAccount:
  create: false
  annotations: {}
  name: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

pdb:
  enabled: false
  minAvailable: 1
