# =========================
# Deployment 설정
# =========================
replicaCount: 2

image:
  repository: dongjukim123/soundory-fe
  pullPolicy: IfNotPresent
  tag: 5

container:
  port: 80  # Vite가 아닌 Nginx 기준 포트

terminationGracePeriodSeconds: 10

resources:
  limits:
    memory: 128Mi
    cpu: 200m
  requests:
    memory: 64Mi
    cpu: 50m

# Nginx는 readOnly로 돌리면 /var/cache/nginx 에러가 남
#podSecurityContext:
# runAsUser: 101
#  fsGroup: 101

# 필요 시 주석처리하거나 제거 가능
# securityContext:
#   allowPrivilegeEscalation: false
#   readOnlyRootFilesystem: true

podAnnotations: {}

# =========================
# Service 설정
# =========================
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# =========================
# Ingress 설정
# =========================
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: soundory-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/success-codes: '200,302'
    alb.ingress.kubernetes.io/healthcheck-path: /
    external-dns.alpha.kubernetes.io/hostname: kimdongju.site
    
  hosts:
    - host: kimdongju.site
      paths:
        - path: /
          pathType: Prefix
  tls: []

# =========================
# HPA 설정
# =========================
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30
  targetMemoryUtilizationPercentage: 50

# =========================
# 헬스체크
# =========================
probes:
  liveness:
    enabled: false
    path: /
  readiness:
    enabled: false
    path: /

# =========================
# 기타 설정
# =========================
pvc:
  enabled: false

serviceAccount:
  create: false
  annotations: {}
  name: ""

nodeSelector: {}
tolerations: []
affinity: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

pdb:
  enabled: false
  minAvailable: 1
