loki:
  serviceMonitor:
    enabled: true
  serviceAccount:
    create: true
    name: loki
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::880076045111:role/loki-sa-role
  loki:
    schemaConfig:
      configs:
      - from: "2024-05-01"
        store: tsdb
        object_store: aws
        schema: v13
        index:
          prefix: index_
          period: 24h

    storageConfig:
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
      aws:
        bucketnames: soundory-loki
        s3: s3://ap-northeast-2

    structuredConfig:
      limits_config:
        allow_structured_metadata: true

      query_scheduler:
        max_outstanding_requests_per_tenant: 32768

      querier:
        max_concurrent: 16
