otel-collector:
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: latest

  mode: deployment
  replicaCount: 1

  service:
    type: ClusterIP

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    processors:
      resource:
        attributes:
          - action: insert
            key: service_name
            from_attribute: service.name      
          - action: insert
            key: loki.resource.labels
            value: service_name   

    exporters:
      otlp/tempo:
        endpoint: tempo-distributor.tempo.svc.cluster.local:4317
        tls:
          insecure: true

      loki:
        endpoint: http://loki-gateway/loki/api/v1/push
        default_labels_enabled:
          exporter: true
          job: true
        tls:
          insecure: true     

      prometheusremotewrite:
        endpoint: http://mimir-nginx.mimir.svc.cluster.local/api/v1/push
        resource_to_telemetry_conversion:
          enabled: true
        headers:
          X-Scope-OrgID: otel-metric  

      debug:                
        verbosity: detailed

    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"

    service:
      telemetry:
        metrics:
          address: "0.0.0.0:8889"
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo] 

        logs:
          receivers: [otlp]
          processors: [resource]   
          exporters: [loki]  

        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]
