---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: al2@latest
  role: arn:aws:iam::880076045111:role/service-eks-node-group-2025052806412355400000000b
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: soundory-cluster
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: soundory-cluster
        Name: soundory-cluster-node

### service pool
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: service-pool
spec:
  template:
    metadata:
      labels:
        node-role: service
    spec:
      expireAfter: 720h
      nodeClassRef:
        name: default
        kind: EC2NodeClass
        group: karpenter.k8s.aws
      requirements:
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["5"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
      taints:
        - key: "node"
          value: "service"
          effect: "NoSchedule"
  limits:
    cpu: 100
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s

### platform pool
---
# apiVersion: karpenter.sh/v1
# kind: NodePool
# metadata:
#   name: platform-pool
# spec:
#   template:
#     metadata:
#       labels:
#         node-role: platform
#     spec:
#       expireAfter: 720h
#       nodeClassRef:
#         name: default
#         kind: EC2NodeClass
#         group: karpenter.k8s.aws
#       requirements:
#         - key: "karpenter.k8s.aws/instance-generation"
#           operator: Gt
#           values: ["5"]
#         - key: karpenter.k8s.aws/instance-category
#           operator: In
#           values: ["c", "m", "r"]
#         - key: kubernetes.io/arch
#           operator: In
#           values: ["amd64"]
#         - key: karpenter.sh/capacity-type
#           operator: In
#           values: ["on-demand"]
#         - key: kubernetes.io/os
#           operator: In
#           values: ["linux"]
#   limits:
#     cpu: 100
#   disruption:
#     consolidationPolicy: WhenEmptyOrUnderutilized
#     consolidateAfter: 30s