apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: node-exporter-priority
value: 100000000
globalDefault: false
description: "Ensure node-exporter DaemonSet preempts less critical pods"
