aws-ebs-csi-driver:
  node:
    loggingFormat: json
  controller:
    enableMetrics: true
    serviceAccount:
      create: true
      name: ebs-csi-driver-sa
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::880076045111:role/ebs-csi-driver-sa-role
  storageClasses:
    - name: ebs
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      provisioner: ebs.csi.aws.com
      parameters:
        type: gp3
        fsType: xfs
      reclaimPolicy: Retain
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true