tempo:
  metaMonitoring:
    serviceMonitor:
      enabled: true

  serviceAccount:
    create: true
    name: tempo
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::880076045111:role/tempo-sa-role

  storage:
    trace:
      backend: s3
      s3:
        endpoint: s3.ap-northeast-2.amazonaws.com
        region: ap-northeast-2
        bucket: soundory-tempo

  traces:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true

  metricsGenerator:
    enabled: true
    config:
      remote_write_add_org_id_header: true
      storage:
        remote_write:
          - url: http://mimir-distributor.mimir.svc.cluster.local:8080/api/v1/push
            headers:
              X-Scope-OrgID: tempo
            send_exemplars: true
      processors:
        - service-graphs
        - span-metrics
      service_graphs:
        dimensions:
          - service.name
          - span.kind
          - http.method
          - http.status_code
      span_metrics:
        dimensions:
          - service.name
          - operation
          - span.kind
          - http.method
          - http.status_code

  global_overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
    per_tenant_override_config: /runtime-config/overrides.yaml

  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
