apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-backend.fullname" . }}-preview
  labels:
    {{- include "my-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-preview
