apiVersion: v2
name: karpenter
description: Umbrella chart for Karpenter
type: application
version: 0.1.0
appVersion: 1.4.0

dependencies:
  - name: karpenter
    version: ~1.4.0
    repository: oci://public.ecr.aws/karpenter

