aws-load-balancer-controller:
  clusterName: soundory-cluster
  serviceAccount:
    create: true
    name: load-balancer-controller-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::880076045111:role/load-balancer-controller-sa-role
  serviceMonitor:
    enabled: true
